apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'ingress-nginx-{{.nameNormalized}}'
      namespace: argocd
    spec:
      destination:
        namespace: 'ingress-nginx'
        name: '{{.nameNormalized}}'
      project: default
      source:
        path: ingress-nginx
        repoURL: "https://github.com/christensenjairus/ArgoCD-Infra"
        targetRevision: main
        kustomize:
          patches:
            - target:
                kind: Service
                name: ingress-nginx-controller
              patch: |-
                - op: add
                  path: /metadata/annotations/metallb.universe.tf~1loadBalancerIPs
                  value: '{{.metadata.annotations.ipv4LbPrefix}}.200,{{.metadata.annotations.ipv6LbPrefix}}::200'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions: []