apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx-extras
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - matrix:
        generators:
          - clusters: {}
          - list:
              elements:
                - exposure: public
                - exposure: private
  template:
    metadata:
      name: 'ingress-nginx-extras-{{.exposure}}-{{.nameNormalized}}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      destination:
        namespace: 'ingress-nginx-extras-{{.exposure}}'
        name: '{{.nameNormalized}}'
      project: default
      source:
        path: ingress-nginx-extras
        repoURL: "https://github.com/christensenjairus/ArgoCD-Infra"
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            toolkit.fluxcd.io/tenant: sre-team
            goldilocks.fairwinds.com/enabled: "true"