apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'ingress-nginx-{{.nameNormalized}}'
      namespace: argocd
    spec:
      destination:
        namespace: 'ingress-nginx'
        name: '{{.nameNormalized}}'
      project: default
      source:
        path: ingress-nginx
        repoURL: "https://github.com/christensenjairus/ArgoCD-Infra"
        targetRevision: main
      kustomize:
        patches:
          - target:
              kind: Service
              name: ingress-nginx-controller
            patch: |-
              - op: add
                path: /metadata/annotations/metallb.universe.tf~1loadBalancerIPs
                value: '{{.metadata.annotations.ipv4LbPrefix}}.{{.lbLastOctetIP}},{{.metadata.annotations.ipv6LbPrefix}}::{{.lbLastOctetIP}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            toolkit.fluxcd.io/tenant: sre-team
            goldilocks.fairwinds.com/enabled: "true"