apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: rook-ceph
    name: argocd-sandbox
  project: default
  sources:
    - chart: rook-ceph
      repoURL: "https://charts.rook.io/release"
      targetRevision: v1.16.0
      helm:
        releaseName: rook-ceph
        valueFiles:
          - $values/rook-ceph/values.yaml
    - repoURL: 'https://github.com/christensenjairus/ArgoCD-Infra.git'
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        toolkit.fluxcd.io/tenant: sre-team
        goldilocks.fairwinds.com/enabled: "true"