apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  destination:
    namespace: rook-ceph-external
    name: argocd-sandbox
  project: default
  source:
    path: rook-ceph
    repoURL: "https://github.com/christensenjairus/ArgoCD-Infra"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        toolkit.fluxcd.io/tenant: sre-team
        goldilocks.fairwinds.com/enabled: "true"