---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: k8s-cephfs
driver: rook-ceph.cephfs.csi.ceph.com
parameters:
  clusterID: "c91cb01333dcfbca965d6e9386b40e8a"
  csi.storage.k8s.io/snapshotter-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph-external
deletionPolicy: Delete
