apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingress-nginx-cache
  namespace: {{.Release.Namespace}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: 'k8s-cephfs'
