apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: rook-csi-rbd-node
  namespace: rook-ceph-external
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  itemPath: vaults/HomeLab K8S/items/Ceph RBD Node