apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-storage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: rook-ceph
    name: in-cluster
  project: default
  source:
    path: storage/rook-operator
    repoURL: "https://github.com/christensenjairus/ArgoCD-Infra"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-storage-configuration
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: rook-ceph-external
    name: in-cluster
  project: default
  source:
    path: storage/rook-external
    repoURL: "https://github.com/christensenjairus/ArgoCD-Infra"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true