apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  install:
    timeout: 20m # takes a while to install because every pod needs to roll out one at a time
  upgrade:
    timeout: 20m
  chart:
    spec:
      chart: cilium
      version: "1.15.x"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
      interval: 12h
  values:
    cluster:
      id: 1
      name: replaceme
    k8sServiceHost: replaceme
    clustermesh:
      apiserver:
        service:
          annotations:
            metallb.universe.tf/loadBalancerIPs: replaceme
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values