apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    toolkit.fluxcd.io/tenant: sre-team
    goldilocks.fairwinds.com/enabled: "true"