controller:
  extraArgs:
    tcp-services-configmap: ingress-nginx-public/tcp-services
    udp-services-configmap: ingress-nginx-public/udp-services
  ingressClassResource:
    name: nginx-public
    controllerValue: k8s.io/nginx-public
  ingressClass: nginx-public
  metrics:
    serviceMonitor:
      namespace: ingress-nginx-public
      namespaceSelector:
        matchNames:
          - ingress-nginx-public