controller:
  extraArgs:
    tcp-services-configmap: ingress-nginx-private/tcp-services
    udp-services-configmap: ingress-nginx-private/udp-services
  ingressClassResource:
    name: nginx-private
    controllerValue: k8s.io/nginx-private
  ingressClass: nginx-private
  metrics:
    serviceMonitor:
      namespace: ingress-nginx-private
      namespaceSelector:
        matchNames:
          - ingress-nginx-private