apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    toolkit.fluxcd.io/tenant: sre-team
    goldilocks.fairwinds.com/enabled: "true"