apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-crds
  namespace: argocd
spec:
  destination:
    namespace: default
    name: in-cluster
  project: default
  source:
    path: crds/manifests
    repoURL: "https://github.com/christensenjairus/ArgoCD-Infra"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true