apiVersion: v2
name: custom-ingress-nginx
description: Combines custom manifests and the upstream ingress-nginx into a single Helm chart.
version: 1.0.0

dependencies:
  - name: ingress-nginx
    version: "4.11.3"
    repository: "https://kubernetes.github.io/ingress-nginx"