apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-cilium-extras
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  goTemplate: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'infra-cilium-extras-{{.nameNormalized}}'
      namespace: argocd
    spec:
      destination:
        namespace: 'kube-system'
        name: '{{.nameNormalized}}'
      project: default
      source:
        path: cilium-extras
        repoURL: "https://github.com/christensenjairus/ArgoCD-Infra"
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true