apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  goTemplate: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'infra-cilium-{{.nameNormalized}}'
      namespace: argocd
    spec:
      destination:
        namespace: 'kube-system'
        name: '{{.nameNormalized}}'
      project: default
      source:
        path: cilium
        repoURL: "https://github.com/christensenjairus/ArgoCD-Infra"
        targetRevision: main
        kustomize:
          patches:
            - target:
                kind: Ingress
                name:
                  hubble
              patch: |
                - op: replace
                  path: /metadata/annotations
                  value:
                    cert-manager.io/cluster-issuer: letsencrypt
                    nginx.ingress.kubernetes.io/ssl-redirect: "true"
                    nginx.ingress.kubernetes.io/custom-http-errors: "400,401,403,404,405,407,408,409,410,411,412,413,418,429,500,502,503,504,505"
                    nginx.ingress.kubernetes.io/auth-method: 'GET'
                    nginx.ingress.kubernetes.io/auth-url: 'http://authelia.authelia.svc.cluster.local:9091/api/authz/auth-request'
                    nginx.ingress.kubernetes.io/auth-signin: 'https://auth.christensencloud.us?rm=$request_method'
                    nginx.ingress.kubernetes.io/auth-response-headers: 'Remote-User,Remote-Name,Remote-Groups,Remote-Email'
      ignoreDifferences:
        - group: "monitoring.coreos.com"
          kind: ServiceMonitors
          jsonPointers:
            - spec/endpoints/relabelings
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=false
          - RespectIgnoreDifferences=true