apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  goTemplate: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'infra-cilium-{{.nameNormalized}}'
      namespace: argocd
    spec:
      destination:
        namespace: 'kube-system'
        name: '{{.nameNormalized}}'
      project: default
      sources:
      - chart: cilium
        repoURL: "https://helm.cilium.io/"
        targetRevision: v1.16.4
        helm:
          releaseName: cilium
          valueFiles:
            - $values/cilium/values.yaml
          valuesObject:
            k8sServiceHost: '{{.metadata.annotations.ipv4LbPrefix}}.100'
      - repoURL: 'https://github.com/christensenjairus/ArgoCD-Infra.git'
        targetRevision: main
        ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
      ignoreDifferences:
        - group: apps
          kind: DaemonSet
          name: cilium
          jsonPointers:
            - /spec/template/spec/containers/0/volumeMounts/0