apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  goTemplate: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'infra-cilium-{{.nameNormalized}}'
      namespace: argocd
    spec:
      destination:
        namespace: 'kube-system'
        name: '{{.nameNormalized}}'
      project: default
      sources:
      - path: networking
        repoURL: "https://github.com/christensenjairus/ArgoCD-Infra"
        targetRevision: main
#        helm:
#          releaseName: cilium
#          valueFiles:
#            - $values/cilium/values.yaml
#          valuesObject:
#            k8sServiceHost: '{{.metadata.annotations.ipv4LbPrefix}}.100'
        kustomize:
          patches:
            - patch: |
                - op: replace
                  path: /metadata/annotations
                  value:
                    cert-manager.io/cluster-issuer: letsencrypt
                    nginx.ingress.kubernetes.io/ssl-redirect: "true"
                    nginx.ingress.kubernetes.io/custom-http-errors: "400,401,403,404,405,407,408,409,410,411,412,413,418,429,500,502,503,504,505"
                    nginx.ingress.kubernetes.io/auth-method: 'GET'
                    nginx.ingress.kubernetes.io/auth-url: 'http://authelia.authelia.svc.cluster.local:9091/api/authz/auth-request'
                    nginx.ingress.kubernetes.io/auth-signin: 'https://auth.christensencloud.us?rm=$request_method'
                    nginx.ingress.kubernetes.io/auth-response-headers: 'Remote-User,Remote-Name,Remote-Groups,Remote-Email'
                - op: replace
                  path: /spec/ingressClassName
                  value: nginx-public
              target:
                kind: Ingress
                name: hubble
            - patch: |
                - op: replace
                  path: /spec/values/cluster/id
                  value: {{.metadata.annotations.clusterID}}
                - op: replace
                  path: /spec/values/cluster/name
                  value: {{.nameNormalized}}
                - op: replace
                  path: /spec/values/k8sServiceHost
                  value: "{{.metadata.annotations.ipv4LbPrefix}}.100"
                - op: replace
                  path: /spec/values/clustermesh/apiserver/service/annotations/metallb.universe.tf~1loadBalancerIPs
                  value: "{{.metadata.annotations.ipv4LbPrefix}}.254"
              target:
                kind: HelmRelease
                name: cilium
      - repoURL: 'https://github.com/christensenjairus/ArgoCD-Infra.git'
        targetRevision: main
        ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - ServerSideApply=true
      ignoreDifferences:
        - group: apps
          kind: DaemonSet
          name: cilium
          jsonPointers:
            - /spec/template/spec/containers/0/volumeMounts/0
        - group: apps
          kind: DaemonSet
          name: cilium-envoy
          jsonPointers:
            - /spec/template/spec/containers/0/volumeMounts/0
        - group: "*"
          kind: "*"
          managedFieldsManagers:
            - cilium