apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'rook-ceph-{{.nameNormalized}}'
      namespace: argocd
    spec:
      destination:
        namespace: rook-ceph-external
        name: '{{.nameNormalized}}'
      project: default
      source:
        path: rook-ceph
        repoURL: "https://github.com/christensenjairus/ArgoCD-Infra"
        targetRevision: main
        kustomize:
          patches:
            - target:
                kind: VolumeSnapshotClass
                name: k8s-rbd
              patch: |-
                - op: replace
                  path: /parameters/clusterID
                  value: '{{.metadata.annotations.radosNamespaceClusterID}}'
            - target:
                kind: VolumeSnapshotClass
                name: k8s-cephfs
              patch: |-
                - op: replace
                  path: /parameters/clusterID
                  value: '{{.metadata.annotations.subvolumeGroupClusterID}}'
            - target:
                kind: StorageClass
                name: k8s-rbd
              patch: |-
                - op: replace
                  path: /parameters/clusterID
                  value: '{{.metadata.annotations.radosNamespaceClusterID}}'
            - target:
                kind: StorageClass
                name: k8s-cephfs
              patch: |-
                - op: replace
                  path: /parameters/clusterID
                  value: '{{.metadata.annotations.subvolumeGroupClusterID}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions: []